---
# See https://github.com/jvautier/project-cli
fullname: jvautier/kv-cli
description: key-value cli to store configs and secrets
tags:
  - python
  - cli
  - secrets
  - configs
github:
  has_issues: true
  has_projects: false
  has_wiki: false
